# Configuration partagée optimisée pour les projets MCP
# Version standardisée 3.7.0 - Janvier 2025

version: "3.7.0"
release_date: "2025-01-08"
standard: "smithery-ai-compliant"

# Configuration des projets MCP
projects:
  hub_central:
    name: "MCP Hub Central"
    path: "./mcp-hub-central"
    type: "hub"
    port: 8080
    domain: "mcp.coupaul.fr"
    description: "Multi-server MCP hub for centralized management"
    smithery_enabled: false  # Hub n'a pas besoin de Smithery
    
  supabase_mcp:
    name: "Supabase MCP Server"
    path: "./ng-supabase-mcp"
    type: "mcp-server"
    port: 8000
    domain: "supabase.mcp.coupaul.fr"
    description: "Enhanced Edition v3.7 - 54+ MCP tools for 100% autonomous Supabase management"
    tools_count: 54
    smithery_enabled: true
    smithery_config: "smithery.yaml"
    
  minecraft_mcp:
    name: "Minecraft MCPC+ 1.6.4 Server"
    path: "./Minecraft-MCP-Forge-1.6.4"
    type: "mcp-server"
    port: 3000
    domain: "minecraft.mcp.coupaul.fr"
    description: "MCPC+ 1.6.4 server management and automation with MCP tools"
    tools_count: 4
    mcpc_version: "1.6.4"
    smithery_enabled: true
    smithery_config: "smithery-metadata.json"

# Configuration commune des APIs
api:
  version: "1.0"
  base_path: "/api"
  endpoints:
    health: "/health"
    mcp: "/mcp"
    tools: "/api/tools"
    config: "/.well-known/mcp-config"
    servers: "/api/servers"

# Configuration commune des variables d'environnement
environment:
  common:
    PYTHON_VERSION: "3.11"
    NODE_VERSION: "18"
    LOG_LEVEL: "INFO"
    HEALTH_CHECK_INTERVAL: 120
    CACHE_DURATION: 300
    TIMEOUT: 15
    
  hub_central:
    PORT: 8080
    MCP_HUB_VERSION: "3.7.0"
    MCP_HUB_NAME: "MCP Hub Central"
    SUPABASE_MCP_URL: "https://supabase.mcp.coupaul.fr"
    MINECRAFT_MCP_URL: "https://minecraft.mcp.coupaul.fr"
    
  supabase_mcp:
    PORT: 8000
    SUPABASE_URL: "https://api.recube.gg/"
    SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY}"
    SUPABASE_SERVICE_ROLE_KEY: "${SUPABASE_SERVICE_ROLE_KEY}"
    SUPABASE_AUTH_JWT_SECRET: "${SUPABASE_AUTH_JWT_SECRET}"
    PRODUCTION_MODE: true
    
  minecraft_mcp:
    PORT: 3000
    MINECRAFT_MCPC_VERSION: "1.6.4"
    DOCKER_ENABLED: true

# Configuration commune du déploiement
deployment:
  platform: "railway"
  docker:
    base_image: "python:3.11-slim"
    health_check: true
    restart_policy: "on-failure"
    max_restarts: 3
  
  domains:
    hub: "mcp.coupaul.fr"
    supabase: "supabase.mcp.coupaul.fr"
    minecraft: "minecraft.mcp.coupaul.fr"

# Configuration commune du monitoring
monitoring:
  enabled: true
  health_check_path: "/health"
  alert_on_failure: true
  log_rotation: true
  metrics_collection: true

# Configuration commune de la sécurité
security:
  ssl_enabled: true
  ssl_verify: true
  rate_limiting: true
  max_requests_per_minute: 100
  api_key_required: false

# Configuration commune des outils
tools:
  auto_discovery: false
  health_check_interval: 120
  cache_duration: 300
  timeout: 15
  retry_attempts: 3

# Configuration commune des notifications
notifications:
  enabled: true
  webhook: "https://hooks.slack.com/services/..."
  email: "admin@mcp.coupaul.fr"
  alert_on_failure: true
  alert_on_recovery: true

# Configuration commune des logs
logging:
  level: "INFO"
  format: "json"
  output: "stdout"
  file_rotation: true
  max_file_size: "10MB"
  max_files: 5

# Configuration commune du cache
cache:
  enabled: true
  ttl: 300
  max_size: "100MB"
  backend: "memory"

# Configuration commune des métriques
metrics:
  enabled: true
  collection_interval: 60
  export_format: "prometheus"
  endpoint: "/metrics"

# Configuration commune des tests
testing:
  enabled: true
  framework: "pytest"
  coverage_threshold: 80
  integration_tests: true
  e2e_tests: true

# Configuration commune de la documentation
documentation:
  enabled: true
  format: "markdown"
  api_docs: true
  readme_template: true
  changelog: true

# Configuration Smithery.ai optimisée
smithery:
  compliance_level: "full"
  metadata_format: "yaml"  # Pour Supabase
  metadata_format_alt: "json"  # Pour Minecraft
  version_sync: true
  auto_publish: true
  quality_checks:
    - "syntax_validation"
    - "tool_schema_validation"
    - "example_validation"
    - "deployment_validation"
  
  # Standards de qualité
  quality_standards:
    min_tools: 1
    max_tools: 100
    required_fields:
      - "name"
      - "version"
      - "description"
      - "author"
      - "license"
      - "repository"
      - "tools"
      - "examples"
    
    # Validation des outils
    tool_validation:
      required_fields:
        - "name"
        - "description"
        - "inputSchema"
      schema_validation: true
      example_validation: true
      
    # Validation des exemples
    example_validation:
      min_examples: 1
      max_examples: 10
      required_fields:
        - "name"
        - "description"
        - "input"