# Railway configuration file
# This file ensures Railway deploys correctly

[build]
builder = "nixpacks"

[deploy]
startCommand = "python mcp_hub_central.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PORT = "8080"
PYTHON_VERSION = "3.11"

[healthcheck]
path = "/health"
timeoutSeconds = 30
intervalSeconds = 10
retries = 3
